### ISSUE TITLE
Test-PSDContentWeb times out searching for driver package(s)

### ISSUE THREAD

**Issue by JerichoJones** [FriendsOfMDT/PSD#140]
It does eventually download the driver package but this is a very slow step as it is waiting to timeout.

`<![LOG[PSDDrivers.ps1: Searching for package(s)]LOG]!><time="11:19:10.857-480" date="03-08-2024" component="PSDDrivers.ps1:89" context="NT AUTHORITY\SYSTEM" type="1" thread="1288" file="PSDDrivers.ps1">
<![LOG[Test-PSDContentWeb: Unable to retrieve directory listing!]LOG]!><time="11:20:50.950-480" date="03-08-2024" component="PSDDeploymentShare.psm1:629" context="NT AUTHORITY\SYSTEM" type="1" thread="1288" file="PSDDeploymentShare.psm1">
<![LOG[Test-PSDContentWeb: System.Net.WebException: The operation has timed out
   at System.Net.HttpWebRequest.GetResponse()
   at CallSite.Target(Closure , CallSite , Object )]LOG]!><time="11:20:50.950-480" date="03-08-2024" component="PSDDeploymentShare.psm1:630" context="NT AUTHORITY\SYSTEM" type="1" thread="1288" file="PSDDeploymentShare.psm1">
<![LOG[Test-PSDContentWeb: ]LOG]!><time="11:20:50.950-480" date="03-08-2024" component="PSDDeploymentShare.psm1:631" context="NT AUTHORITY\SYSTEM" type="1" thread="1288" file="PSDDeploymentShare.psm1">
<![LOG[Test-PSDContentWeb: Unable to retrieve directory listing!]LOG]!><time="11:22:35.973-480" date="03-08-2024" component="PSDDeploymentShare.psm1:629" context="NT AUTHORITY\SYSTEM" type="1" thread="1288" file="PSDDeploymentShare.psm1">
<![LOG[Test-PSDContentWeb: System.Net.WebException: The operation has timed out
   at System.Net.HttpWebRequest.GetResponse()
   at CallSite.Target(Closure , CallSite , Object )]LOG]!><time="11:22:35.973-480" date="03-08-2024" component="PSDDeploymentShare.psm1:630" context="NT AUTHORITY\SYSTEM" type="1" thread="1288" file="PSDDeploymentShare.psm1">
<![LOG[Test-PSDContentWeb: ]LOG]!><time="11:22:35.973-480" date="03-08-2024" component="PSDDeploymentShare.psm1:631" context="NT AUTHORITY\SYSTEM" type="1" thread="1288" file="PSDDeploymentShare.psm1">
`

**Comment by JerichoJones** [comment]
Weirdly, I added more logging steps to identify where the issue was occurring and now it's gone. Chalk it up to network wonkiness...
