### ISSUE TITLE
Cannot bind parameter 'Path' to the target.

### ISSUE THREAD

**Issue by brianfgonzalez** [FriendsOfMDT/PSD#35]
I received no errors when running the "Install-PSD.ps1", but when i attempted to import an OS .wim I received this exception message.

System.Management.Automation.ParameterBindingException: Cannot bind parameter 'Path' to the target. Exception setting "Path": "Cannot find path 'PSD:\Operating Systems' because it does not exist." ---> System.Management.Automation.SetValueInvocationException: Exception setting "Path": "Cannot find path 'PSD:\Operating Systems' because it does not exist." ---> System.Management.Automation.ItemNotFoundException: Cannot find path 'PSD:\Operating Systems' because it does not exist.
   at System.Management.Automation.LocationGlobber.ExpandMshGlobPath(String path, Boolean allowNonexistingPaths, PSDriveInfo drive, ContainerCmdletProvider provider, CmdletProviderContext context)
   at System.Management.Automation.LocationGlobber.ResolveDriveQualifiedPath(String path, CmdletProviderContext context, Boolean allowNonexistingPaths, CmdletProvider& providerInstance)
   at System.Management.Automation.LocationGlobber.GetGlobbedMonadPathsFromMonadPath(String path, Boolean allowNonexistingPaths, CmdletProviderContext context, CmdletProvider& providerInstance)
   at System.Management.Automation.LocationGlobber.GetGlobbedProviderPathsFromMonadPath(String path, Boolean allowNonexistingPaths, CmdletProviderContext context, ProviderInfo& provider, CmdletProvider& providerInstance)
   at System.Management.Automation.SessionStateInternal.GetItem(String[] paths, CmdletProviderContext context)
   at System.Management.Automation.SessionStateInternal.GetItem(String[] paths, Boolean force, Boolean literalPath)
   at Microsoft.BDD.PSSnapIn.ImportOperatingSystem.set_Path(String value)
   at System.Management.Automation.ReflectionParameterBinder.BindParameter(String name, Object value, CompiledCommandParameter parameterMetadata)
   --- End of inner exception stack trace ---
   at System.Management.Automation.ReflectionParameterBinder.BindParameter(String name, Object value, CompiledCommandParameter parameterMetadata)
   at System.Management.Automation.ParameterBinderBase.BindParameter(CommandParameterInternal parameter, CompiledCommandParameter parameterMetadata, ParameterBindingFlags flags)
   --- End of inner exception stack trace ---
   at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
   at Microsoft.BDD.Wizards.OperatingSystemProgress.WizardProcessing()
   at Microsoft.BDD.Wizards.WizardProgress.InitiateWizardProcessing()

/BG

**Comment by brianfgonzalez** [comment]
This may not be an issue, I un-mounted the new share in the deployment workbench and re-added it and now it's working..

**Comment by soupman98** [comment]
Thanks for the update @brianfgonzalez . Closing this issue.
